baseURL = 'https://nyaohpopo.com/' # 仮のドメインに修正 (必ずマスターのドメインに合わせること!)
languageCode = 'ja-jp'
title = 'Nyaoh popo!'
theme = 'stack'
copyright = "Nyaoh popo! All Rights Reserved." # コピーライトを正式な表記に修正

[params]

  customCSS = ["/css/custom.css"] 

  SEOTitle = "にゃおぽぽ"
  description = "学生による小さな小さなゲームの隠れ場"

  # Stackテーマのプロフィール設定を追加（アバター/ロゴとして使われるわ）
  [params.profile]
    # ここに画像ファイルを指定する (Stackテーマは /images/ の下を探すことが多いわ)
    avatar = "/images/nyaohpopo-logo.png" 
    # ヘッダーに表示するタイトル
    name = "Nyaoh popo!" 
    # プロフィール下の説明
    bio = "世界を目指す原石のために"

  # =======================================================
  # ▼▼▼【新規追加】ソーシャルメディアリンク ▼▼▼
  # 企業サイトには必須よ！フッターにアイコンが表示されるわ。
  # =======================================================
  # TwitterやInstagramなどのアカウントがあれば設定する。
  # Twitter (X)
  twitter = "https://twitter.com/nyaoh_popo_official" 
  
  # Instagram
  instagram = "https://instagram.com/nyaoh_popo_official" 
  
  # GitHub (技術系企業なら)
  github = "https://github.com/nyaohpopo-team" 


# =======================================================
# ▼▼▼【修正】メニュー設定 ▼▼▼
# サイトについて → 企業情報 (よりビジネスっぽく)
# =======================================================
[[menu.main]]
  name = "サービス"
  url = "/services/"
  weight = 10

[[menu.main]]
  name = "企業情報" # 名称をよりビジネスライクに変更
  url = "/about/" 
  weight = 20

[[menu.main]]
  name = "ブログ/ニュース" # ブログがあれば追加
  url = "/posts/" 
  weight = 30
  
[[menu.main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 40

# =======================================================
# ▼▼▼【重要】アセット処理の設定 ▼▼▼
# HugoがCSSやSassファイルを正しく処理するために必要よ！
# =======================================================
[build]
  writeStats = true
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # HTMLタグをMarkdown内で使えるようにする（ビジュアル化に役立つ）

[processing]
  [processing.css]
    # CSSの処理を有効にする
    enable = true