baseURL = 'https://nyaohpopo.cc/' # 仮のドメインに修正 (必ずマスターのドメインに合わせること!)
languageCode = 'ja-jp'
title = 'にゃおぽぽ'
theme = 'stack'
copyright = "Nyaoh popo All Rights Reserved." # コピーライトを正式な表記に修正

[params]
  customCSS = [
    "css/extended/avatar.css",
    "css/extended/links.css",
    "css/extended/cards.css",
    "css/extended/colors.css"
  ]

[params.profile]
  avatar = "/images/avatar.png"
  name = "Nyaoh"
  bio = "世界を目指す原石のために"